name: pipeline

env:
  ForcedZigVersion: 0.14.0

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup zig
        uses: mlugg/setup-zig@v1
        with:
          version: ${{env.ForcedZigVersion}}

      - name: build
        run: zig build

      - name: test
        run: zig build test
